# Generated by Django 4.2.7 on 2026-06-07 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('academic_year', models.CharField(default='2025-26', max_length=10)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('ai', 'AI')], default='basic', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'db_table': 'schools',
            },
        ),
    ]
