# Generated by Django 4.2.7 on 2026-06-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
